import type { Metadata } from "next";

// @ts-ignore - side-effect CSS import without typings
import './globals.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme='winter'>
      <body>
        {children}
      </body>
    </html>
  );
}
