import type { Metadata } from "next";

// @ts-ignore - side-effect CSS import without typings
import "./globals.css";
import Navbar from "./Navbar";
import AuthProvider from "./authProvider/Provider";
import GoogleAnalytic from "./GoogleAnalytic";

//fonts
// import localFont from "next/font/local";
import {Roboto} from "next/font/google";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const robotTo = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});


// const popin = localFont({
//   src: "../public/fonts/CalSans-SemiBold.woff2",
//   variable: "--font-cal",
// });


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter">
      <body className={robotTo.className}>
        <GoogleAnalytic />
        <AuthProvider>
          <Navbar />
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
